steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - research/svi_score_v3/cloud/Dockerfile
      - --tag
      - ${_IMAGE_URI}
      - .
images:
  - ${_IMAGE_URI}
options:
  logging: CLOUD_LOGGING_ONLY
