# Three-channel AMSS reference scenario for the V10 external-transport study.
#
# `paid_social_proxy` is generated by AMSS's public, unchanged
# DefaultTraditionalMediaModule. It is an exposure-media stress proxy placed in
# V9's paid-social role; it is not claimed to reproduce a platform auction.

build_v10_amss_three_channel_scenario <- function(seed = 31001L) {
  if (!requireNamespace("amss", quietly = TRUE)) {
    stop("The pinned AMSS package is required.")
  }

  set.seed(seed)

  n.years <- 4L
  time.n <- n.years * 52L
  budget.index <- rep(seq_len(n.years), each = 52L)

  activity.transition <- matrix(
    rep(c(0.60, 0.30, 0.10), 3L),
    nrow = length(amss::kActivityStates),
    byrow = TRUE
  )
  favorability.transition <- matrix(
    rep(c(0.03, 0.07, 0.65, 0.20, 0.05), 5L),
    nrow = length(amss::kFavorabilityStates),
    byrow = TRUE
  )
  market.rate.nonoise <- amss::SimulateSinusoidal(
    time.n,
    52,
    vert.translation = 0.6,
    amplitude = 0.25
  )
  market.rate.seas <- pmax(
    0,
    pmin(
      1,
      market.rate.nonoise *
        amss::SimulateAR1(length(market.rate.nonoise), 1, 0.1, 0.3)
    )
  )
  nat.mig.params <- list(
    population = 2.4e8,
    market.rate.trend = 0.68,
    market.rate.seas = market.rate.seas,
    prop.activity = c(0.375, 0.425, 0.2),
    prop.favorability = c(0.03, 0.07, 0.65, 0.20, 0.05),
    prop.loyalty = c(1, 0, 0),
    transition.matrices = list(
      activity = activity.transition,
      favorability = favorability.transition
    )
  )

  # Paid-social stress proxy. Spend is persistent and positively associated
  # with latent market demand, creating realistic planning confounding. Only
  # realized spend/volume are observable downstream; market.rate.seas remains
  # hidden from Flux.
  paid.social.planning <- as.numeric(amss::SimulateCorrelated(
    market.rate.seas,
    cor.vx = 0.55,
    mu.x = 1,
    sigma.x = 0.30
  ))
  paid.social.pacing <- amss::SimulateAR1(time.n, 0, 0.18, 0.60)
  paid.social.flighting <- pmax(
    0.05,
    paid.social.planning + paid.social.pacing
  )
  paid.social.activity.trans.mat <- matrix(
    c(
      0.45, 0.50, 0.05,
      0.00, 0.70, 0.30,
      0.00, 0.00, 1.00
    ),
    nrow = length(amss::kActivityStates),
    byrow = TRUE
  )
  paid.social.favorability.trans.mat <- matrix(
    c(
      0.55, 0.00, 0.30, 0.12, 0.03,
      0.00, 0.80, 0.15, 0.05, 0.00,
      0.00, 0.00, 0.65, 0.30, 0.05,
      0.00, 0.00, 0.00, 0.85, 0.15,
      0.00, 0.00, 0.00, 0.00, 1.00
    ),
    nrow = length(amss::kFavorabilityStates),
    byrow = TRUE
  )
  params.paid.social.proxy <- list(
    audience.membership = list(
      activity = c(0.15, 0.55, 0.45),
      favorability = c(0.25, 0.35, 0.65, 0.80, 0.90)
    ),
    budget = c(18e6, 22e6, 28e6, 34e6),
    budget.index = budget.index,
    flighting = paid.social.flighting,
    unit.cost = 0.008,
    hill.ec = 2.2,
    hill.slope = 1.3,
    transition.matrices = list(
      activity = paid.social.activity.trans.mat,
      favorability = paid.social.favorability.trans.mat
    )
  )

  # Paid search: the native AMSS query/auction module from the official
  # vignette, mapped to V9's nonbrand-search archetype.
  spend.cap.fn <- function(time.index, budget, budget.index) {
    if ((time.index %% 13) > 1) Inf else 0
  }
  bid.fn <- function(time.index, per.capita.budget, budget.index) 1.1
  kwl.fn <- function(time.index, per.capita.budget, budget.index) {
    4.5 * per.capita.budget
  }
  search.activity.trans.mat <- matrix(
    c(
      0.05, 0.95, 0.00,
      0.00, 0.85, 0.15,
      0.00, 0.00, 1.00
    ),
    nrow = length(amss::kActivityStates),
    byrow = TRUE
  )
  params.search <- list(
    audience.membership = list(activity = c(0.01, 0.3, 0.4)),
    budget = (2.4e7 / n.years) * seq_len(n.years),
    budget.index = budget.index,
    spend.cap.fn = spend.cap.fn,
    bid.fn = bid.fn,
    kwl.fn = kwl.fn,
    query.rate = 1,
    cpc.min = 0.8,
    cpc.max = 1.1,
    ctr = list(activity = c(0.005, 0.08, 0.10)),
    relative.effectiveness = c(0, 0.1, 1),
    transition.matrices = list(
      activity = search.activity.trans.mat,
      favorability = diag(length(amss::kFavorabilityStates))
    )
  )

  # Long-memory reach-media role: the native traditional TV module from the
  # official vignette, mapped to V9's CTV archetype with that caveat retained.
  tv.flighting <- pmax(
    0,
    market.rate.seas +
      amss::SimulateAR1(length(market.rate.seas), -0.7, 0.7, -0.7)
  )
  tv.flighting <- tv.flighting[c(6:length(tv.flighting), 1:5)]
  tv.favorability.trans.mat <- matrix(
    c(
      0.4, 0.0, 0.4, 0.2, 0.0,
      0.0, 0.9, 0.1, 0.0, 0.0,
      0.0, 0.0, 0.6, 0.4, 0.0,
      0.0, 0.0, 0.0, 0.8, 0.2,
      0.0, 0.0, 0.0, 0.0, 1.0
    ),
    nrow = length(amss::kFavorabilityStates),
    byrow = TRUE
  )
  params.tv <- list(
    audience.membership = list(activity = rep(0.4, 3)),
    budget = rep(c(545e5, 475e5, 420e5, 455e5), length = n.years),
    budget.index = budget.index,
    flighting = tv.flighting,
    unit.cost = 0.005,
    hill.ec = 1.56,
    hill.slope = 1,
    transition.matrices = list(
      activity = diag(length(amss::kActivityStates)),
      favorability = tv.favorability.trans.mat
    )
  )

  sales.params <- list(
    competitor.demand.max = list(loyalty = c(0.8, 0, 0.8)),
    advertiser.demand.slope = list(favorability = rep(0, 5)),
    advertiser.demand.intercept = list(
      favorability = c(0.014, 0, 0.2, 0.3, 0.9)
    ),
    price = 80
  )

  list(
    simulation.args = list(
      time.n = time.n,
      nat.mig.params = nat.mig.params,
      media.names = c("paid_social_proxy", "search", "tv"),
      media.modules = c(
        amss::DefaultTraditionalMediaModule,
        amss::DefaultSearchMediaModule,
        amss::DefaultTraditionalMediaModule
      ),
      media.params = list(
        params.paid.social.proxy,
        params.search,
        params.tv
      ),
      sales.params = sales.params,
      ping = time.n
    ),
    hidden.design = list(
      seed = seed,
      market.rate.seas = market.rate.seas,
      paid.social.planning.correlation = 0.55
    )
  )
}
